package javier.peralta.lenguadesignos.lista;

import java.util.ArrayList;
import java.util.List;

import javier.peralta.lenguadesignos.R;
import javier.peralta.lenguadesignos.clase.Signo;

public class ListaPalabras {

    public static List<Signo> getList(){
        List<Signo> lista = new ArrayList<>();

        // Familia
        lista.add(new Signo(R.drawable.abajo, "Abajo", "Familia"));
        lista.add(new Signo(R.drawable.abuelo, "Abuelo", "Familia"));
        lista.add(new Signo(R.drawable.amigo, "Amigo", "Familia"));
        lista.add(new Signo(R.drawable.bebe, "Bebé", "Familia"));
        lista.add(new Signo(R.drawable.hermano, "Hermano", "Familia"));
        lista.add(new Signo(R.drawable.mama, "Mamá", "Familia"));
        lista.add(new Signo(R.drawable.nina, "Niña", "Familia"));
        lista.add(new Signo(R.drawable.nino, "Niño", "Familia"));
        lista.add(new Signo(R.drawable.papa, "Papá", "Familia"));
        lista.add(new Signo(R.drawable.persona, "Persona", "Familia"));
        lista.add(new Signo(R.drawable.primo, "Primo", "Familia"));
        lista.add(new Signo(R.drawable.tio, "Tío", "Familia"));
        lista.add(new Signo(R.drawable.ciego, "Ciego", "Familia"));
        lista.add(new Signo(R.drawable.sordo, "Sordo", "Familia"));
        lista.add(new Signo(R.drawable.sordociego, "Sordociego", "Familia"));


        // Comidas y bebidas
        lista.add(new Signo(R.drawable.comida, "Comida", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.bebida, "Bebida", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.desayuno, "Desayuno", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.comida, "Comida", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.merienda, "Merienda", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.cena, "Cena", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.alimento, "Alimento", "Comidas y bebidas"));
        // lista.add(new Signo(R.drawable.hambre, "Hambre", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.sed, "Sed", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.aceite, "Aceite", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.agua, "Agua", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.arroz, "Arroz", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.azucar, "Azúcar", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.bocadillo, "Bocadillo", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.caramelo, "Caramelo", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.carnes, "Carne", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.cebolla, "Cebolla", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.chocolate, "Chocolate", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.galleta, "Galleta", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.huevo, "Huevo", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.leche, "Leche", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.lechuga, "Lechuga", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.limon, "Limón", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.macarrones, "Macarrones", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.pan, "Pan", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.patata, "Patata", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.pescado, "Pescado", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.pollo, "Pollo", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.pure, "Puré", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.queso, "Queso", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.sal, "Sal", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.sopa, "Sopa", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.tomate, "Tomate", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.zanahoria, "Zanahoria", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.zumo, "Zumo", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.postre, "Postre", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.dulce, "Dulce", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.flan, "Flan", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.fresa, "Fresa", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.fruta, "Fruta", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.helado, "Helado", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.manzana, "Manzana", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.naranja, "Naranja", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.pera, "Pera", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.platano, "Plátano", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.sandia, "Sandía", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.tarta, "Tarta", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.uva, "Uva", "Comidas y bebidas"));
        lista.add(new Signo(R.drawable.yogur, "Yogur", "Comidas y bebidas"));



        // Ropa
        lista.add(new Signo(R.drawable.ropa, "Ropa", "Ropa"));
        lista.add(new Signo(R.drawable.abrigo, "Abrigo", "Ropa"));
        lista.add(new Signo(R.drawable.banador_chico, "Bañador Chico", "Ropa"));
        lista.add(new Signo(R.drawable.banador_chica, "Bañador Chica", "Ropa"));
        lista.add(new Signo(R.drawable.braga, "Braga", "Ropa"));
        lista.add(new Signo(R.drawable.bufanda, "Bufanda", "Ropa"));
        lista.add(new Signo(R.drawable.calzoncillo, "Calzoncillo", "Ropa"));
        lista.add(new Signo(R.drawable.camisa, "Camisa", "Ropa"));
        lista.add(new Signo(R.drawable.chandal, "Chándal", "Ropa"));
        lista.add(new Signo(R.drawable.gafas, "Gafas", "Ropa"));
        lista.add(new Signo(R.drawable.gorra, "Gorra", "Ropa"));
        lista.add(new Signo(R.drawable.jersey, "Jersey", "Ropa"));
        lista.add(new Signo(R.drawable.mochila, "Mochila", "Ropa"));
        lista.add(new Signo(R.drawable.pantalon, "Pantalón", "Ropa"));
        lista.add(new Signo(R.drawable.pijama, "Pijama", "Ropa"));
        lista.add(new Signo(R.drawable.reloj, "Reloj", "Ropa"));
        lista.add(new Signo(R.drawable.zapatilla, "Zapatilla", "Ropa"));
        lista.add(new Signo(R.drawable.zapato, "Zapato", "Ropa"));



        // Cuerpo
        lista.add(new Signo(R.drawable.cuerpo, "Cuerpo", "Cuerpo"));
        lista.add(new Signo(R.drawable.boca, "Boca", "Cuerpo"));
        lista.add(new Signo(R.drawable.brazo, "Brazo", "Cuerpo"));
        lista.add(new Signo(R.drawable.cabeza, "Cabeza", "Cuerpo"));
        lista.add(new Signo(R.drawable.culo, "Culo", "Cuerpo"));
        lista.add(new Signo(R.drawable.dedo, "Dedo", "Cuerpo"));
        lista.add(new Signo(R.drawable.dientes, "Dientes", "Cuerpo"));
        lista.add(new Signo(R.drawable.lengua, "Lengua", "Cuerpo"));
        lista.add(new Signo(R.drawable.mano, "Mano", "Cuerpo"));
        lista.add(new Signo(R.drawable.nariz, "Nariz", "Cuerpo"));
        lista.add(new Signo(R.drawable.ojo, "Ojo", "Cuerpo"));
        lista.add(new Signo(R.drawable.oreja, "Oreja", "Cuerpo"));
        lista.add(new Signo(R.drawable.pelo, "Pelo", "Cuerpo"));
        lista.add(new Signo(R.drawable.pene, "Pene", "Cuerpo"));
        lista.add(new Signo(R.drawable.pie, "Pie", "Cuerpo"));
        lista.add(new Signo(R.drawable.pierna, "Pierna", "Cuerpo"));
        lista.add(new Signo(R.drawable.vulva, "Vulva", "Cuerpo"));
        lista.add(new Signo(R.drawable.sentidos, "Sentidos", "Cuerpo"));
        lista.add(new Signo(R.drawable.gusto, "Gusto", "Cuerpo"));
        lista.add(new Signo(R.drawable.oido, "Oído", "Cuerpo"));
        lista.add(new Signo(R.drawable.olfato, "Olfato", "Cuerpo"));
        lista.add(new Signo(R.drawable.tacto, "Tacto", "Cuerpo"));
        lista.add(new Signo(R.drawable.vista, "Vista", "Cuerpo"));



        // Casa
        lista.add(new Signo(R.drawable.casa, "Casa", "Casa"));
        lista.add(new Signo(R.drawable.cocina, "Cocina", "Casa"));
        lista.add(new Signo(R.drawable.bano, "Cuarto de baño", "Casa"));
        lista.add(new Signo(R.drawable.dormitorio, "Dormitorio", "Casa"));
        lista.add(new Signo(R.drawable.salon, "Salón", "Casa"));
        lista.add(new Signo(R.drawable.alfombra, "Alfombra", "Casa"));
        lista.add(new Signo(R.drawable.armario, "Armario", "Casa"));
        lista.add(new Signo(R.drawable.cama, "Cama", "Casa"));
        lista.add(new Signo(R.drawable.cristal, "Cristal", "Casa"));
        lista.add(new Signo(R.drawable.despertador, "Despertador", "Casa"));
        lista.add(new Signo(R.drawable.fax, "Fax", "Casa"));
        lista.add(new Signo(R.drawable.lampara, "Lámpara", "Casa"));
        lista.add(new Signo(R.drawable.maceta, "Maceta", "Casa"));
        lista.add(new Signo(R.drawable.manta, "Manta", "Casa"));
        lista.add(new Signo(R.drawable.maquina, "Máquina", "Casa"));
        lista.add(new Signo(R.drawable.mesa, "Mesa", "Casa"));
        lista.add(new Signo(R.drawable.mesilla, "Mesilla", "Casa"));
        lista.add(new Signo(R.drawable.mueble, "Mueble", "Casa"));
        lista.add(new Signo(R.drawable.muneco, "Muñeco", "Casa"));
        lista.add(new Signo(R.drawable.objeto, "Objeto", "Casa"));
        lista.add(new Signo(R.drawable.ordenador, "Ordenador", "Casa"));
        lista.add(new Signo(R.drawable.pelota, "Pelota", "Casa"));
        lista.add(new Signo(R.drawable.plancha, "Plancha", "Casa"));
        lista.add(new Signo(R.drawable.puerta, "Puerta", "Casa"));
        lista.add(new Signo(R.drawable.sabana, "Sábana", "Casa"));
        lista.add(new Signo(R.drawable.silla, "Silla", "Casa"));
        lista.add(new Signo(R.drawable.sofa, "Sofá", "Casa"));
        lista.add(new Signo(R.drawable.telefono, "Teléfono", "Casa"));
        lista.add(new Signo(R.drawable.televisor, "Televisor", "Casa"));
        lista.add(new Signo(R.drawable.ventana, "Ventana", "Casa"));
        lista.add(new Signo(R.drawable.video, "Vídeo", "Casa"));
        lista.add(new Signo(R.drawable.objetos, "Objetos", "Casa"));
        lista.add(new Signo(R.drawable.bano, "Baño", "Casa"));
        lista.add(new Signo(R.drawable.banera, "Bañera", "Casa"));
        lista.add(new Signo(R.drawable.cepillo, "Cepillo de dientes", "Casa"));
        lista.add(new Signo(R.drawable.champu, "Champú", "Casa"));
        lista.add(new Signo(R.drawable.colonia, "Colonia", "Casa"));
        lista.add(new Signo(R.drawable.espejo, "Espejo", "Casa"));
        lista.add(new Signo(R.drawable.esponja, "Esponja", "Casa"));
        lista.add(new Signo(R.drawable.jabon, "Jabón", "Casa"));
        lista.add(new Signo(R.drawable.lavabo, "Lavabo", "Casa"));
        lista.add(new Signo(R.drawable.papel, "Papel higiénico", "Casa"));
        lista.add(new Signo(R.drawable.pasta_de_dientes, "Pasta de dientes", "Casa"));
        lista.add(new Signo(R.drawable.peine, "Peine", "Casa"));
        lista.add(new Signo(R.drawable.toalla, "Toalla", "Casa"));
        lista.add(new Signo(R.drawable.cocina, "Cocina", "Casa"));
        lista.add(new Signo(R.drawable.cacerola, "Cacerola", "Casa"));
        lista.add(new Signo(R.drawable.cuchara, "Cuchara", "Casa"));
        lista.add(new Signo(R.drawable.cuchillo, "Cuchillo", "Casa"));
        lista.add(new Signo(R.drawable.jarra, "Jarra", "Casa"));
        lista.add(new Signo(R.drawable.lavadora, "Lavadora", "Casa"));
        lista.add(new Signo(R.drawable.nevera, "Nevera", "Casa"));
        lista.add(new Signo(R.drawable.plato, "Plato", "Casa"));
        lista.add(new Signo(R.drawable.sarten, "Sartén", "Casa"));
        lista.add(new Signo(R.drawable.servilleta, "Servilleta", "Casa"));
        lista.add(new Signo(R.drawable.tenedor, "Tenedor", "Casa"));
        lista.add(new Signo(R.drawable.vaso, "Vaso", "Casa"));


        // Colegio
        // Colegio
        lista.add(new Signo(R.drawable.colegio, "Colegio", "Colegio"));
        lista.add(new Signo(R.drawable.abecedario, "Abecedario", "Colegio"));
        lista.add(new Signo(R.drawable.alumno, "Alumno/alumna", "Colegio"));
        lista.add(new Signo(R.drawable.clase, "Clase", "Colegio"));
        lista.add(new Signo(R.drawable.dibujo, "Dibujo", "Colegio"));
        lista.add(new Signo(R.drawable.diferencia, "Diferencia", "Colegio"));
        lista.add(new Signo(R.drawable.gramo, "Gramo", "Colegio"));
        lista.add(new Signo(R.drawable.lenguajessignosespa_ola, "Lengua de signos española", "Colegio"));
        lista.add(new Signo(R.drawable.litro, "Litro", "Colegio"));
        lista.add(new Signo(R.drawable.medida, "Medida", "Colegio"));
        lista.add(new Signo(R.drawable.metro, "Metro", "Colegio"));
        lista.add(new Signo(R.drawable.multiplicacion, "Multiplicación", "Colegio"));
        lista.add(new Signo(R.drawable.numero, "Número", "Colegio"));
        lista.add(new Signo(R.drawable.palabra, "Palabra", "Colegio"));
        lista.add(new Signo(R.drawable.patio, "Patio", "Colegio"));
        lista.add(new Signo(R.drawable.resta, "Resta", "Colegio"));
        lista.add(new Signo(R.drawable.servicio, "Servicio", "Colegio"));
        lista.add(new Signo(R.drawable.suma, "Suma", "Colegio"));
        lista.add(new Signo(R.drawable.cosas_del_colegio, "Cosas del colegio", "Colegio"));
        lista.add(new Signo(R.drawable.boligrafo, "Bolígrafo", "Colegio"));
        lista.add(new Signo(R.drawable.borrador, "Borrador", "Colegio"));
        lista.add(new Signo(R.drawable.cera, "Cera", "Colegio"));
        lista.add(new Signo(R.drawable.cosas, "Cosa", "Colegio"));
        lista.add(new Signo(R.drawable.cuaderno, "Cuaderno", "Colegio"));
        lista.add(new Signo(R.drawable.cuento, "Cuento", "Colegio"));
        lista.add(new Signo(R.drawable.diccionario, "Diccionario", "Colegio"));
        lista.add(new Signo(R.drawable.goma, "Goma", "Colegio"));
        lista.add(new Signo(R.drawable.hoja, "Hoja", "Colegio"));
        lista.add(new Signo(R.drawable.lapices_de_colores, "Lápices de colores", "Colegio"));
        lista.add(new Signo(R.drawable.lapiz, "Lápiz", "Colegio"));
        lista.add(new Signo(R.drawable.libro, "Libro", "Colegio"));
        lista.add(new Signo(R.drawable.papel, "Papel", "Colegio"));
        lista.add(new Signo(R.drawable.papelera, "Papelera", "Colegio"));
        lista.add(new Signo(R.drawable.pegamento, "Pegamento", "Colegio"));
        lista.add(new Signo(R.drawable.pintura, "Pintura", "Colegio"));
        lista.add(new Signo(R.drawable.pizarra, "Pizarra", "Colegio"));
        lista.add(new Signo(R.drawable.plastilina, "Plastilina", "Colegio"));
        lista.add(new Signo(R.drawable.rotulador, "Rotulador", "Colegio"));
        lista.add(new Signo(R.drawable.sacapuntas, "Sacapuntas", "Colegio"));
        lista.add(new Signo(R.drawable.tijeras, "Tijeras", "Colegio"));
        lista.add(new Signo(R.drawable.tiza, "Tiza", "Colegio"));
        lista.add(new Signo(R.drawable.colores, "Colores", "Colegio"));
        lista.add(new Signo(R.drawable.amarillo, "Amarillo", "Colegio"));
        lista.add(new Signo(R.drawable.azul, "Azul", "Colegio"));
        lista.add(new Signo(R.drawable.blanco, "Blanco", "Colegio"));
        lista.add(new Signo(R.drawable.marron, "Marrón", "Colegio"));
        lista.add(new Signo(R.drawable.naranja, "Naranja", "Colegio"));
        lista.add(new Signo(R.drawable.negro, "Negro", "Colegio"));
        lista.add(new Signo(R.drawable.rojo, "Rojo", "Colegio"));
        lista.add(new Signo(R.drawable.rosa, "Rosa", "Colegio"));
        lista.add(new Signo(R.drawable.verde, "Verde", "Colegio"));
        lista.add(new Signo(R.drawable.formas_y_tamanos, "Formas y tamaños", "Colegio"));
        lista.add(new Signo(R.drawable.formas, "Formas", "Colegio"));
        lista.add(new Signo(R.drawable.circulo, "Círculo", "Colegio"));
        lista.add(new Signo(R.drawable.cuadrado, "Cuadrado", "Colegio"));
        lista.add(new Signo(R.drawable.rectangulo, "Rectángulo", "Colegio"));
        lista.add(new Signo(R.drawable.triangulo, "Triángulo", "Colegio"));
        lista.add(new Signo(R.drawable.grande, "Tamaño Grande", "Colegio"));
        lista.add(new Signo(R.drawable.mediano, "Tamaño Mediano", "Colegio"));
        lista.add(new Signo(R.drawable.pequeno, "Tamaño Pequeño", "Colegio"));



        // Ciudad
        // Ciudad
        lista.add(new Signo(R.drawable.ciudad, "Ciudad", "Ciudad"));
        lista.add(new Signo(R.drawable.acera, "Acera", "Ciudad"));
        lista.add(new Signo(R.drawable.banco_dinero, "Banco", "Ciudad"));
        lista.add(new Signo(R.drawable.biblioteca, "Biblioteca", "Ciudad"));
        lista.add(new Signo(R.drawable.buzon, "Buzón", "Ciudad"));
        lista.add(new Signo(R.drawable.calle, "Calle", "Ciudad"));
        lista.add(new Signo(R.drawable.cine, "Cine", "Ciudad"));
        lista.add(new Signo(R.drawable.colegio, "Colegio", "Ciudad"));
        lista.add(new Signo(R.drawable.columpio, "Columpio", "Ciudad"));
        lista.add(new Signo(R.drawable.farola, "Farola", "Ciudad"));
        lista.add(new Signo(R.drawable.fuente, "Fuente", "Ciudad"));
        lista.add(new Signo(R.drawable.hospital, "Hospital", "Ciudad"));
        lista.add(new Signo(R.drawable.libreria, "Librería", "Ciudad"));
        lista.add(new Signo(R.drawable.luz, "Luz", "Ciudad"));
        lista.add(new Signo(R.drawable.museo, "Museo", "Ciudad"));
        lista.add(new Signo(R.drawable.parque, "Parque", "Ciudad"));
        lista.add(new Signo(R.drawable.paso_de_cebra, "Paso de cebra", "Ciudad"));
        lista.add(new Signo(R.drawable.pasteleria, "Pastelería", "Ciudad"));
        lista.add(new Signo(R.drawable.plaza, "Plaza", "Ciudad"));
        lista.add(new Signo(R.drawable.puente, "Puente", "Ciudad"));
        lista.add(new Signo(R.drawable.quiosco, "Quiosco", "Ciudad"));
        lista.add(new Signo(R.drawable.semaforo, "Semáforo", "Ciudad"));
        lista.add(new Signo(R.drawable.supermercado, "Supermercado", "Ciudad"));
        lista.add(new Signo(R.drawable.teatro, "Teatro", "Ciudad"));
        lista.add(new Signo(R.drawable.tienda, "Tienda", "Ciudad"));
        lista.add(new Signo(R.drawable.tobogan, "Tobogán", "Ciudad"));
        lista.add(new Signo(R.drawable.zapateria, "Zapatería", "Ciudad"));
        lista.add(new Signo(R.drawable.transporte, "Transporte", "Ciudad"));
        lista.add(new Signo(R.drawable.vehiculo, "Vehículos", "Ciudad"));
        lista.add(new Signo(R.drawable.ambulancia, "Ambulancia", "Ciudad"));
        lista.add(new Signo(R.drawable.autobus, "Autobús", "Ciudad"));
        lista.add(new Signo(R.drawable.barca, "Barca", "Ciudad"));
        lista.add(new Signo(R.drawable.bicicleta, "Bicicleta", "Ciudad"));
        lista.add(new Signo(R.drawable.camion, "Camión", "Ciudad"));
        lista.add(new Signo(R.drawable.coche, "Coche", "Ciudad"));
        lista.add(new Signo(R.drawable.moto, "Moto", "Ciudad"));
        lista.add(new Signo(R.drawable.profesiones, "Profesiones", "Ciudad"));
        lista.add(new Signo(R.drawable.bombero, "Bombero/bombera", "Ciudad"));
        lista.add(new Signo(R.drawable.medico, "Médico/médica", "Ciudad"));
        lista.add(new Signo(R.drawable.pastelero, "Pastelero/pastelera", "Ciudad"));
        lista.add(new Signo(R.drawable.pescador, "Pescador/pescadera", "Ciudad"));
        lista.add(new Signo(R.drawable.policia, "Policía", "Ciudad"));
        lista.add(new Signo(R.drawable.profesor, "Profesor/profesora", "Ciudad"));



        // Calendario
        // Calendario
        lista.add(new Signo(R.drawable.calendario, "Calendario", "Calendario"));
        lista.add(new Signo(R.drawable.ano, "Año", "Calendario"));
        lista.add(new Signo(R.drawable.mes, "Mes", "Calendario"));
        lista.add(new Signo(R.drawable.enero, "Enero", "Calendario"));
        lista.add(new Signo(R.drawable.febrero, "Febrero", "Calendario"));
        lista.add(new Signo(R.drawable.marzo, "Marzo", "Calendario"));
        lista.add(new Signo(R.drawable.abril, "Abril", "Calendario"));
        lista.add(new Signo(R.drawable.mayo, "Mayo", "Calendario"));
        lista.add(new Signo(R.drawable.junio, "Junio", "Calendario"));
        lista.add(new Signo(R.drawable.julio, "Julio", "Calendario"));
        lista.add(new Signo(R.drawable.agosto, "Agosto", "Calendario"));
        lista.add(new Signo(R.drawable.septiembre, "Septiembre", "Calendario"));
        lista.add(new Signo(R.drawable.octubre, "Octubre", "Calendario"));
        lista.add(new Signo(R.drawable.noviembre, "Noviembre", "Calendario"));
        lista.add(new Signo(R.drawable.diciembre, "Diciembre", "Calendario"));
        lista.add(new Signo(R.drawable.dia_de_la_semana, "Día", "Calendario"));
        lista.add(new Signo(R.drawable.semana, "Semana", "Calendario"));
        lista.add(new Signo(R.drawable.lunes, "Lunes", "Calendario"));
        lista.add(new Signo(R.drawable.martes, "Martes", "Calendario"));
        lista.add(new Signo(R.drawable.miercoles, "Miércoles", "Calendario"));
        lista.add(new Signo(R.drawable.jueves, "Jueves", "Calendario"));
        lista.add(new Signo(R.drawable.viernes, "Viernes", "Calendario"));
        lista.add(new Signo(R.drawable.sabado, "Sábado", "Calendario"));
        lista.add(new Signo(R.drawable.domingo, "Domingo", "Calendario"));
        lista.add(new Signo(R.drawable.fin_de_semana, "Fin de semana", "Calendario"));
        lista.add(new Signo(R.drawable.estaciones, "Estaciones", "Calendario"));
        lista.add(new Signo(R.drawable.primavera, "Primavera", "Calendario"));
        lista.add(new Signo(R.drawable.verano, "Verano", "Calendario"));
        lista.add(new Signo(R.drawable.otono, "Otoño", "Calendario"));
        lista.add(new Signo(R.drawable.invierno, "Invierno", "Calendario"));
        lista.add(new Signo(R.drawable.tiempo, "Tiempo", "Calendario"));
        lista.add(new Signo(R.drawable.ayer, "Ayer", "Calendario"));
        lista.add(new Signo(R.drawable.hoy, "Hoy", "Calendario"));
        lista.add(new Signo(R.drawable.manana, "Mañana", "Calendario"));
        lista.add(new Signo(R.drawable.por_la_manana, "Por la mañana", "Calendario"));
        lista.add(new Signo(R.drawable.por_la_tarde, "Por la tarde", "Calendario"));
        lista.add(new Signo(R.drawable.por_la_noche, "Por la noche", "Calendario"));
        lista.add(new Signo(R.drawable.la_hora_de, "La hora de...", "Calendario"));
        lista.add(new Signo(R.drawable.hora_interrogativa, "¿Qué hora es?", "Calendario"));
        lista.add(new Signo(R.drawable.en_punto, "En punto", "Calendario"));
        lista.add(new Signo(R.drawable.y_cuarto, "Y cuarto", "Calendario"));
        lista.add(new Signo(R.drawable.y_media, "Y media", "Calendario"));
        lista.add(new Signo(R.drawable.menos_cuarto, "Menos cuarto", "Calendario"));
        lista.add(new Signo(R.drawable.fiesta, "Fiesta", "Calendario"));
        lista.add(new Signo(R.drawable.cumpleanos, "Cumpleaños", "Calendario"));
        lista.add(new Signo(R.drawable.navidad, "Navidad", "Calendario"));
        lista.add(new Signo(R.drawable.papa_noel, "Papá Noel", "Calendario"));
        lista.add(new Signo(R.drawable.reyes_magos, "Reyes Magos", "Calendario"));


        // Naturaleza
        lista.add(new Signo(R.drawable.naturaleza, "Naturaleza", "Naturaleza"));
        lista.add(new Signo(R.drawable.abeto, "Abeto", "Naturaleza"));
        lista.add(new Signo(R.drawable.arbol, "Árbol", "Naturaleza"));
        lista.add(new Signo(R.drawable.arco_iris, "Arco iris", "Naturaleza"));
        lista.add(new Signo(R.drawable.arena, "Arena", "Naturaleza"));
        lista.add(new Signo(R.drawable.estrella, "Estrella", "Naturaleza"));
        lista.add(new Signo(R.drawable.faro, "Faro", "Naturaleza"));
        lista.add(new Signo(R.drawable.flor, "Flor", "Naturaleza"));
        lista.add(new Signo(R.drawable.flotador, "Flotador", "Naturaleza"));
        lista.add(new Signo(R.drawable.fuego, "Fuego", "Naturaleza"));
        lista.add(new Signo(R.drawable.hierba, "Hierba", "Naturaleza"));
        lista.add(new Signo(R.drawable.hoja, "Hoja", "Naturaleza"));
        lista.add(new Signo(R.drawable.lago, "Lago", "Naturaleza"));
        lista.add(new Signo(R.drawable.luna, "Luna", "Naturaleza"));
        lista.add(new Signo(R.drawable.mar, "Mar", "Naturaleza"));
        lista.add(new Signo(R.drawable.margarita, "Margarita", "Naturaleza"));
        lista.add(new Signo(R.drawable.montana, "Montaña", "Naturaleza"));
        lista.add(new Signo(R.drawable.palmera, "Palmera", "Naturaleza"));
        lista.add(new Signo(R.drawable.piedra, "Piedra", "Naturaleza"));
        lista.add(new Signo(R.drawable.playa, "Playa", "Naturaleza"));
        lista.add(new Signo(R.drawable.pozo, "Pozo", "Naturaleza"));
        lista.add(new Signo(R.drawable.rio, "Río", "Naturaleza"));
        lista.add(new Signo(R.drawable.saco_de_dormir, "Saco de dormir", "Naturaleza"));
        lista.add(new Signo(R.drawable.sombrilla, "Sombrilla", "Naturaleza"));
        lista.add(new Signo(R.drawable.tienda_campana, "Tienda de campaña", "Naturaleza"));
        lista.add(new Signo(R.drawable.tiempo, "Tiempo", "Naturaleza"));
        lista.add(new Signo(R.drawable.calor, "Calor", "Naturaleza"));
        lista.add(new Signo(R.drawable.frio, "Frío", "Naturaleza"));
        lista.add(new Signo(R.drawable.lluvia, "Lluvia", "Naturaleza"));
        lista.add(new Signo(R.drawable.nieve, "Nieve", "Naturaleza"));
        lista.add(new Signo(R.drawable.nube, "Nube", "Naturaleza"));
        lista.add(new Signo(R.drawable.nublado, "Nublado/nublada", "Naturaleza"));
        lista.add(new Signo(R.drawable.sol, "Sol", "Naturaleza"));
        lista.add(new Signo(R.drawable.tormenta, "Tormenta", "Naturaleza"));
        lista.add(new Signo(R.drawable.viento, "Viento", "Naturaleza"));
        lista.add(new Signo(R.drawable.animal, "Animal", "Naturaleza"));
        lista.add(new Signo(R.drawable.abeja, "Abeja", "Naturaleza"));
        lista.add(new Signo(R.drawable.aguila, "Águila", "Naturaleza"));
        lista.add(new Signo(R.drawable.ballena, "Ballena", "Naturaleza"));
        lista.add(new Signo(R.drawable.burro, "Burro/burra", "Naturaleza"));
        lista.add(new Signo(R.drawable.caballo, "Caballo", "Naturaleza"));
        lista.add(new Signo(R.drawable.cabra, "Cabra", "Naturaleza"));
        lista.add(new Signo(R.drawable.camello, "Camello/camella", "Naturaleza"));
        lista.add(new Signo(R.drawable.cerdo, "Cerdo/cerda", "Naturaleza"));
        lista.add(new Signo(R.drawable.cocodrilo, "Cocodrilo", "Naturaleza"));
        lista.add(new Signo(R.drawable.conejo, "Conejo/coneja", "Naturaleza"));
        lista.add(new Signo(R.drawable.delfin, "Delfín", "Naturaleza"));
        lista.add(new Signo(R.drawable.elefante, "Elefante/elefanta", "Naturaleza"));
        lista.add(new Signo(R.drawable.foca, "Foca", "Naturaleza"));
        lista.add(new Signo(R.drawable.gallina, "Gallina", "Naturaleza"));
        lista.add(new Signo(R.drawable.gato, "Gato/gata", "Naturaleza"));
        lista.add(new Signo(R.drawable.granja, "Granja", "Naturaleza"));
        lista.add(new Signo(R.drawable.jirafa, "Jirafa", "Naturaleza"));
        lista.add(new Signo(R.drawable.leon, "León/leona", "Naturaleza"));
        lista.add(new Signo(R.drawable.loro, "Loro", "Naturaleza"));
        lista.add(new Signo(R.drawable.mariposa, "Mariposa", "Naturaleza"));
        lista.add(new Signo(R.drawable.mono, "Mono/mona", "Naturaleza"));
        lista.add(new Signo(R.drawable.oso, "Oso/osa", "Naturaleza"));
        lista.add(new Signo(R.drawable.oveja, "Oveja", "Naturaleza"));
        lista.add(new Signo(R.drawable.pajaro, "Pájaro", "Naturaleza"));
        lista.add(new Signo(R.drawable.pato, "Pato/pata", "Naturaleza"));
        lista.add(new Signo(R.drawable.perro, "Perro/perra", "Naturaleza"));
        lista.add(new Signo(R.drawable.tiburon, "Tiburón", "Naturaleza"));
        lista.add(new Signo(R.drawable.tigre, "Tigre/tigresa", "Naturaleza"));
        lista.add(new Signo(R.drawable.toro, "Toro", "Naturaleza"));
        lista.add(new Signo(R.drawable.tortuga, "Tortuga", "Naturaleza"));
        lista.add(new Signo(R.drawable.vaca, "Vaca", "Naturaleza"));
        lista.add(new Signo(R.drawable.zoo, "Zoo", "Naturaleza"));




        // Adjetivos, adverbios y verbos
        lista.add(new Signo(R.drawable.adjetivos, "Adjetivos", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.aburrido, "Aburrido/aburrida", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.acido, "Ácido/ácida", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.agradable, "Agradable", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.alegre, "Alegre", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.alto, "Alto/alta", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.amargo, "Amargo/amarga", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.bajo, "Bajo/baja", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.blando, "Blando/blanda", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.bueno, "Bueno/buena", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.caliente, "Caliente", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.castano, "Castaño/castaña", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.claro, "Claro/clara", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.contento, "Contento/contenta", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.delgado, "Delgado/delgada", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.desagradable, "Desagradable", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.diferente, "Diferente", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.divertido, "Divertido/divertida", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.dulce, "Dulce", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.duro, "Duro/dura", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.enfadado, "Enfadado/enfadada", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.enfermo, "Enfermo/enferma", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.feo, "Feo/fea", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.frio, "Frío/fría", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.gordo, "Gordo/gorda", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.guapo, "Guapo/guapa", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.igual, "Igual", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.lento, "Lento/lenta", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.limpio, "Limpio/limpia", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.lleno, "Lleno/llena", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.malo, "Malo/mala", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.moreno, "Moreno/morena", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.mucho, "Muchos/muchas", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.oscuro, "Oscuro/oscura", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.pelirrojo, "Pelirrojo/pelirroja", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.poco, "Pocos/pocas", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.primer, "Primer/primero/primera", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.rapido, "Rápido/rápida", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.rubio, "Rubio/rubia", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.salado, "Salado/salada", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.sano, "Sano/sana", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.sucio, "Sucio/sucia", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.templado, "Templado/templada", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.triste, "Triste", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.ultimo, "Último/última", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.vacio, "Vacío", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.adverbio, "Adverbios", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.derecha, "A la derecha", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.izquierda, "A la izquierda", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.abajo, "Abajo", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.arriba, "Arriba", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.bien, "Bien", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.cerca, "Cerca", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.debajo, "Debajo", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.delante, "Delante", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.dentro, "Dentro", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.detras, "Detrás", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.encima, "Encima", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.fuera, "Fuera", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.lejos, "Lejos", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.mal, "Mal", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.verbo, "Verbo", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.abrazar, "Abrazar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.amar, "Amar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.andar, "Andar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.aprender, "Aprender", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.ayudar, "Ayudar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.beber, "Beber", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.besar, "Besar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.comer, "Comer", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.comprar, "Comprar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.conocer, "Conocer", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.contar, "Contar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.correr, "Correr", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.cortar, "Cortar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.crecer, "Crecer", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.crecer_planta, "Crecer (Planta)", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.descansar, "Descansar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.dormir, "Dormir", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.ducharse, "Ducharse", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.entender, "Entender", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.escribir, "Escribir", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.esperar, "Esperar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.explicar, "Explicar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.gritar, "Gritar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.gustar, "Gustar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.hablar, "Hablar (Lengua de Signos)", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.hablar_oral, "Hablar (Lengua oral)", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.jugar, "Jugar", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.lavar_la_ropa, "Lavar la ropa", "Adjetivos, adverbios y verbos"));
        lista.add(new Signo(R.drawable.lavar_la_cabeza, "Lavarse la cabeza", "Adjetivos, adverbios y verbos"));


        // Saludos y preguntas
        lista.add(new Signo(R.drawable.preguntas, "Preguntas", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.como_se_dice, "¿Cómo se dice?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.como_se_signa, "¿Cómo se signa?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.como, "¿Cómo?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.cual, "¿Cuál?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.cuando_pasado, "¿Cuándo? (Pasado)", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.cuando_presente_y_futuro, "¿Cuándo? (Presente y futuro)", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.cuanto, "¿Cuánto?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.donde, "¿Dónde?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.por, "¿Por qué?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.para, "¿Para qué?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.que_dia_es, "¿Qué día es?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.que_dice, "¿Qué dice?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.que, "¿Qué tal?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.que, "¿Qué?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.quien, "¿Quién?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.si_o_no, "¿Sí o no?", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.saludo, "Saludo", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.cortesia, "Cortesía", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.adios, "Adiós", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.buenas_noches, "Buenas noches", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.buenas_tardes, "Buenas tardes", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.buenos_dias, "Buenos días", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.cuidado, "¡Cuidado!", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.de_nada, "De nada", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.gracias, "Gracias", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.hola, "Hola", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.no, "No", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.nombre, "Nombre", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.por_favor, "Por favor", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.si, "Sí", "Saludos y preguntas"));
        lista.add(new Signo(R.drawable.signo, "Signo", "Saludos y preguntas"));
        return lista;
    }


}
